name: Continuous Deployment (Prod)

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: $ {{ secrets.DOCKER_USERNAME }}
          password: $ {{ secrets.DOCKER_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push school image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ak2733/argocd_week37.2:${{github.sha}}
      - name: Clone argo-deployment rep, update image tags, and push tags
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git clone https://github.com/AbdulBasit2733/argo-deployment.git
          
          sed -i 's|image: ak2733/argocd_week37.2:.*|image: ak2733/argocd_week37.2:${{github.sha}}|' manifest.yml
          
          git config user.name "Github Actions Bot"
          git config user.email "actions@github.com"

          git add .
          git commit -m "Update Argocd Practice image tags to ${{github.sha}}"
          git push https://${PAT}@github.com/AbdulBasit2733/argo-deployment.git

